clear;
clc;
close all;
[U1,u1,~]=ErrorSolutiont(0.5,0.1,1);
x=-80:0.5:80-0.5;
U2=U1(:,1);
figure;
plot(x, U2, 'LineWidth', 2);
xlabel('x');
ylabel('u(x, 0)');
title('t=0');
grid on;
U3=U1(:,51);
figure;
plot(x, U3, 'LineWidth', 2);
xlabel('x');
ylabel('u(x, 0)');
title('t=5');
grid on;
U4=U1(:,101);
figure;
plot(x, U4, 'LineWidth', 2);
xlabel('x');
ylabel('u(x, 0)');
title('t=10');
grid on;
U5=U1(:,151);
figure;
plot(x, U5, 'LineWidth', 2);
xlabel('x');
ylabel('u(x, 0)');
title('t=15');
grid on;
U5=U1(:,201);
figure;
plot(x, U5, 'LineWidth', 2);
xlabel('x');
ylabel('u(x, 0)');
title('t=20');
grid on;
