function [f_x,f_y,dp_dx,dp_dy,adv_u,adv_v,u_raw,v_raw,u_bar,v_bar] = mms_source_func(t,x,y,nu,alpha)
%MMS_SOURCE_FUNC
%    [F_X,F_Y,DP_DX,DP_DY,ADV_U,ADV_V,U_RAW,V_RAW,U_BAR,V_BAR] = MMS_SOURCE_FUNC(T,X,Y,NU,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2025-11-23 16:06:29

t2 = pi.^2;
t3 = pi.^3;
t5 = alpha.^2;
t6 = x.*pi.*2.0;
t7 = y.*pi.*2.0;
t8 = -t;
t4 = t2.^2;
t9 = exp(t8);
t10 = cos(t6);
t11 = cos(t7);
t12 = sin(t6);
t13 = sin(t7);
t14 = t9.*t12.*t13;
t15 = t9.*t10.*t13.*pi.*2.0;
t16 = t9.*t11.*t12.*pi.*2.0;
t19 = t9.*t10.*t11.*pi.*2.0;
t22 = t3.*t5.*t9.*t10.*t13.*1.6e+1;
t23 = t3.*t5.*t9.*t11.*t12.*1.6e+1;
t17 = t14.*pi.*2.0;
t18 = -t14;
t21 = t2.*t14.*8.0;
t25 = t2.*t5.*t14.*-8.0;
t26 = t4.*t5.*t14.*6.4e+1;
t28 = t15+t22;
t29 = t16+t23;
t20 = -t17;
t24 = t5.*t21;
t30 = t21+t26;
t32 = t14.*t28;
t33 = t14.*t29;
t27 = t14+t24;
t31 = nu.*t30;
t34 = t32+t33;
f_x = t18+t19+t25+t31+t34;
if nargout > 1
    f_y = t18+t20+t25+t31+t34;
end
if nargout > 2
    dp_dx = t19;
end
if nargout > 3
    dp_dy = t20;
end
if nargout > 4
    adv_u = t34;
end
if nargout > 5
    adv_v = t34;
end
if nargout > 6
    u_raw = t27;
end
if nargout > 7
    v_raw = t27;
end
if nargout > 8
    u_bar = t14;
end
if nargout > 9
    v_bar = t14;
end
end
